mqtt:
  host: "127.0.0.1"
  port: 1883
  username: "user"
  password: "pass"
  keepalive: 60

database:
  mongo_url: "mongodb://localhost:27017"
  db_name: "virtual_devices"

devices:
  air_conditioners:
    pid: 1101
    auto_update:
      count: 2
      update_interval: 10
    static:
      count: 1

  lights:
    pid: 1201
    auto_update:
      count: 3
      update_interval: 5
    static:
      count: 2

  temperature_sensors:
    pid: 1301
    auto_update:
      count: 2
      update_interval: 6
      range: [18, 32]
    static:
      count: 1

  humidity_sensors:
    pid: 1302
    auto_update:
      count: 1
      update_interval: 7
      range: [30, 90]
    static:
      count: 1

  motion_sensors:
    pid: 1303
    auto_update:
      count: 1
      update_interval: 8
      range: [0, 1]  # 是否有人体感应
    static:
      count: 1
